import type { Metadata } from "next";
import { Quicksand } from "@next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "GP221",
  description: "Generated by create next app",
};

const inter = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
  fallback: ["system-ui", "arial"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
